const HTML = `<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>관리</title><script>(function(){try{var saved=localStorage.getItem('dashboard_theme');document.documentElement.classList.add(saved==='dark'?'dark':'light')}catch(e){document.documentElement.classList.add('light')}})();</script><script src="https://accounts.google.com/gsi/client" async></script>
<style>
:root{--bg:#f4f5f7;--panel:#fff;--text:#22252a;--muted:#777d87;--line:#e7e9ed;--accent:#f5821f;--accent2:#ffad62}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 85% 0,#fff0e2 0,transparent 28%),var(--bg);color:var(--text);font-family:system-ui,-apple-system,"Noto Sans KR",sans-serif}.wrap{max-width:1080px;margin:0 auto;padding:42px 22px 70px}.header{display:flex;align-items:center;justify-content:space-between;margin-bottom:22px}.brand{display:flex;align-items:center;gap:12px}.logo{display:grid;place-items:center;width:42px;height:42px;border-radius:14px;background:linear-gradient(135deg,var(--accent),var(--accent2));color:white;font-size:20px;box-shadow:0 8px 20px #f5821f40}h1{font-size:25px;margin:0}.subtitle{color:var(--muted);font-size:13px;margin-top:2px}.actions,.ranges{display:flex;gap:8px}button{font:inherit}.icon-btn,.range{border:1px solid var(--line);background:var(--panel);color:var(--text);border-radius:10px;padding:9px 12px;cursor:pointer}.range.active{background:var(--accent);border-color:var(--accent);color:#fff}.card,.panel{background:color-mix(in srgb,var(--panel) 94%,transparent);border:1px solid var(--line);border-radius:18px;box-shadow:0 8px 28px rgba(36,39,44,.06)}.login,.loading{text-align:center;padding:70px 20px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.card{padding:20px}.label{color:var(--muted);font-size:13px}.value{font-size:32px;font-weight:800;margin-top:8px}.panel{margin-top:15px;padding:20px}.panel-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:16px}.panel h2{font-size:16px;margin:0}.chart{height:230px;width:100%;overflow:visible}.chart .gridline{stroke:var(--line);stroke-width:1}.chart .area{fill:url(#areaGradient)}.chart .line{fill:none;stroke:var(--accent);stroke-width:3;stroke-linecap:round;stroke-linejoin:round}.chart .dot{fill:var(--panel);stroke:var(--accent);stroke-width:2}.chart-labels{display:flex;justify-content:space-between;color:var(--muted);font-size:11px;margin-top:4px}.tables{display:grid;grid-template-columns:1.2fr .8fr;gap:15px}table{width:100%;border-collapse:collapse}th,td{padding:12px 8px;text-align:left;border-bottom:1px solid var(--line);font-size:13px}th{color:var(--muted);font-weight:600}tr:last-child td{border-bottom:0}.right{text-align:right}.bar{height:6px;background:var(--line);border-radius:9px;overflow:hidden;margin-top:5px}.bar i{display:block;height:100%;background:linear-gradient(90deg,var(--accent),var(--accent2));border-radius:inherit}.error{color:#b42318;white-space:pre-wrap}.empty{color:var(--muted)}
body{min-height:100vh;background-repeat:no-repeat!important;background-attachment:fixed!important;background-size:100vw 100vh!important}.ranges::before{content:'조회 기간';align-self:center;margin-right:4px;color:var(--accent);font-size:13px;font-weight:700}.chart .dot{cursor:pointer;transition:r .18s ease,stroke-width .18s ease}.chart .dot:hover,.chart .dot:focus,.chart .dot.selected{r:7px;stroke-width:3px;outline:none}.logo{background:transparent;box-shadow:none;color:var(--text);font-size:25px;width:32px}.login{max-width:440px;margin:72px auto 0;padding:44px 38px;display:flex;flex-direction:column;align-items:center;gap:22px}.login[hidden]{display:none}.login::before{content:'🔒';display:grid;place-items:center;width:52px;height:52px;border-radius:50%;background:color-mix(in srgb,var(--accent) 14%,var(--panel));font-size:22px}.login p{margin:0;text-align:center;color:var(--muted);line-height:1.6}.login p strong{display:block;color:var(--text);font-size:20px;margin-bottom:5px}.login #button{display:flex;justify-content:center}.actions{visibility:hidden}html.authorized .actions{visibility:visible}html.theme-transition *,html.theme-transition *::before,html.theme-transition *::after{transition:background-color .35s ease,color .28s ease,border-color .35s ease,box-shadow .35s ease!important}html.theme-transition body{transition:background-color .4s ease!important}.grid{grid-template-columns:repeat(4,1fr)}@media(prefers-color-scheme:dark){:root{--bg:#17191d;--panel:#22252a;--text:#f2f3f5;--muted:#a7adb7;--line:#353941}body{background:radial-gradient(circle at 85% 0,#382414 0,transparent 28%),var(--bg)}}html.dark{--bg:#17191d;--panel:#22252a;--text:#f2f3f5;--muted:#a7adb7;--line:#353941}html.dark body{background:radial-gradient(circle at 85% 0,#382414 0,transparent 28%),var(--bg)}html.light{--bg:#f4f5f7;--panel:#fff;--text:#22252a;--muted:#777d87;--line:#e7e9ed}html.light body{background:radial-gradient(circle at 85% 0,#fff0e2 0,transparent 28%),var(--bg)}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:720px){.wrap{padding:24px 14px 50px}.header{align-items:flex-start}.subtitle{display:none}.grid{grid-template-columns:1fr}.tables{grid-template-columns:1fr}.actions button span{display:none}.chart{height:180px}.login{margin-top:38px;padding:36px 22px}}
</style></head><body><main class="wrap"><header class="header"><div class="brand"><div class="logo">↗</div><div><h1>Resume Analytics</h1><div class="subtitle">이력서 방문 현황을 한눈에 확인하세요</div></div></div><div class="actions"><button class="icon-btn" onclick="refreshData()">↻ <span>새로고침</span></button><button class="icon-btn" onclick="logout()">로그아웃</button></div></header><section id="login" class="card login" hidden><p>본인 Google 계정으로 로그인해주세요.</p><div id="button"></div></section><section id="loading" class="card loading">통계를 불러오는 중입니다.</section><section id="dashboard" hidden><div class="grid"><div class="card"><div class="label">오늘 방문자</div><div id="today" class="value">-</div></div><div class="card"><div class="label">선택 기간 방문자</div><div id="week" class="value">-</div></div><div class="card"><div class="label">선택 기간 조회수</div><div id="views" class="value">-</div></div><div class="card"><div class="label">이전 기간 대비</div><div id="change" class="value">-</div></div></div><section class="panel"><div class="panel-head"><h2>일별 방문 추이</h2><div class="ranges"><button class="range active" data-days="7" onclick="setRange(7)">7일</button><button class="range" data-days="30" onclick="setRange(30)">30일</button></div></div><svg id="chart" class="chart" viewBox="0 0 800 220" preserveAspectRatio="none"></svg><div id="chartLabels" class="chart-labels"></div></section><div class="tables"><section class="panel"><h2>시간대별 방문</h2><table><thead><tr><th>시간</th><th class="right">방문자</th></tr></thead><tbody id="hours"></tbody></table></section><section class="panel"><h2>접속 기기</h2><table><thead><tr><th>기기</th><th class="right">방문자</th></tr></thead><tbody id="devices"></tbody></table></section></div><div class="tables"><section class="panel"><h2>인기 페이지 · 평균 체류</h2><table><thead><tr><th>페이지</th><th class="right">조회수 / 체류</th></tr></thead><tbody id="pages"></tbody></table></section><section class="panel"><h2>첫 진입 페이지</h2><table><thead><tr><th>페이지</th><th class="right">세션</th></tr></thead><tbody id="landings"></tbody></table></section></div><div class="tables"><section class="panel"><h2>방문 도시</h2><table><thead><tr><th>도시</th><th class="right">방문자</th></tr></thead><tbody id="cities"></tbody></table></section><section class="panel"><h2>최근 방문 요약</h2><table><thead><tr><th>시간 · 환경</th><th class="right">방문자</th></tr></thead><tbody id="recent"></tbody></table></section></div><section class="panel"><h2>외부 유입 경로</h2><table><thead><tr><th>소스</th><th>매체</th><th class="right">방문자</th></tr></thead><tbody id="sources"></tbody></table></section></section></main>
<script>
let days=7,activeStart='',activeEnd='';
async function login(response){const session=await fetch('/api/session',{method:'POST',headers:{Authorization:'Bearer '+response.credential}});if(!session.ok){document.querySelector('#login').innerHTML='<p class="error">허용되지 않은 계정입니다.</p>';return}document.querySelector('#login').hidden=true;await loadData()}
async function loadData(initial=false,selectedDate='',start='',end='',preserveChart=false){const dashboard=document.querySelector('#dashboard'),hasData=!dashboard.hidden;if(hasData)setSectionsLoading(true);else{dashboard.hidden=true;document.querySelector('#loading').hidden=false;document.querySelector('#loading').classList.remove('error');document.querySelector('#loading').textContent='권한을 확인하는 중입니다.'}const query=selectedDate?'&date='+selectedDate:(start&&end?'&start='+start+'&end='+end:'');const r=await fetch('/api/report?days='+days+query);if(r.status===401){setSectionsLoading(false);document.querySelector('#loading').hidden=true;document.querySelector('#login').hidden=false;return}if(!r.ok){setSectionsLoading(false);if(hasData){alert('지표를 불러오지 못했습니다.');return}document.querySelector('#loading').classList.add('error');document.querySelector('#loading').textContent=await r.text();return}setAuthorizedUi();const d=await r.json();document.querySelector('#login').hidden=true;document.querySelector('#loading').hidden=true;dashboard.hidden=false;const singleDay=!!selectedDate||(start&&start===end),labels=document.querySelectorAll('.grid .label');labels[0].textContent=singleDay?'선택일 방문자':'오늘 방문자';labels[1].textContent=singleDay?'선택일 방문자':'선택 기간 방문자';labels[2].textContent=singleDay?'선택일 조회수':'선택 기간 조회수';labels[3].textContent=singleDay?'전일 대비':'이전 기간 대비';document.querySelector('.panel-head h2').textContent='방문 현황';today.textContent=d.today;week.textContent=d.week;views.textContent=d.views;change.textContent=(d.change>0?'+':'')+d.change+'%';change.style.color=d.change>=0?'#16803c':'#b42318';fill('sources',d.sources,3);fillBars('cities',d.cities);fillBars('devices',d.devices.map(r=>[deviceName(r[0]),r[1]]));fillBars('hours',d.hours.map(r=>[r[0]+'시',r[1]]));fillBars('landings',d.landings);fillBars('pages',d.pages.map(r=>[r[0],r[1]+'회 · '+duration(r[2]),r[1]]));fillBars('recent',d.recent.map(r=>[recentLabel(r),r[3]]));if(!preserveChart&&!singleDay)drawChart(d.daily);syncSelectedDots();setSectionsLoading(false)}
function setSectionsLoading(active){document.querySelectorAll('#dashboard .card,#dashboard .panel').forEach(section=>section.classList.toggle('is-loading',active))}
function setRange(n){days=n;setPresetDates(n);document.querySelector('.ranges').classList.remove('custom-range');document.querySelectorAll('.range').forEach(b=>b.classList.toggle('active',+b.dataset.days===n));loadData()}function selectDate(raw){applyGraphRange(raw,raw)}function applyGraphRange(rawStart,rawEnd){const first=rawStart<=rawEnd?rawStart:rawEnd,last=rawStart<=rawEnd?rawEnd:rawStart,start=rawToIso(first),end=rawToIso(last);activeStart=first;activeEnd=last;startDate.value=start;endDate.value=end;document.querySelector('.ranges').classList.add('custom-range');document.querySelectorAll('.range').forEach(b=>b.classList.remove('active'));syncSelectedDots();loadData(false,'',start,end,true)}function applyDateRange(){const start=startDate.value,end=endDate.value;if(!start||!end||start>end){alert('올바른 조회 기간을 선택해주세요.');return}activeStart=start.replaceAll('-','');activeEnd=end.replaceAll('-','');document.querySelector('.ranges').classList.add('custom-range');document.querySelectorAll('.range,.dot,.hit-area').forEach(b=>b.classList.remove('active','selected'));syncSelectedDots();loadData(false,'',start,end)}function setPresetDates(n){const end=new Date(),start=new Date();start.setDate(end.getDate()-(n-1));startDate.value=localIso(start);endDate.value=localIso(end);activeStart=startDate.value.replaceAll('-','');activeEnd=endDate.value.replaceAll('-','')}function rawToIso(raw){return raw.slice(0,4)+'-'+raw.slice(4,6)+'-'+raw.slice(6,8)}function localIso(date){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return y+'-'+m+'-'+d}function refreshData(){const active=document.querySelector('.range.active');active?loadData():applyDateRange()}async function logout(){await fetch('/api/logout',{method:'POST'});google.accounts.id.disableAutoSelect();location.reload()}
function fill(id,rows,n){document.querySelector('#'+id).innerHTML=rows.map(r=>'<tr>'+r.slice(0,n).map((v,i)=>'<td class="'+(i===n-1?'right':'')+'">'+escapeHtml(v)+'</td>').join('')+'</tr>').join('')||'<tr><td class="empty" colspan="'+n+'">데이터 없음</td></tr>'}
function fillBars(id,rows){const metric=r=>+(r[2]??r[1]),max=Math.max(1,...rows.map(metric));document.querySelector('#'+id).innerHTML=rows.map(r=>'<tr><td>'+escapeHtml(localize(r[0]))+'<div class="bar"><i style="width:'+Math.max(6,metric(r)/max*100)+'%"></i></div></td><td class="right">'+escapeHtml(r[1])+'</td></tr>').join('')||'<tr><td class="empty" colspan="2">데이터 없음</td></tr>'}
function localize(v){if(!v)return '알 수 없음';return ({'Bucheon-si':'부천시','Seoul':'서울','Incheon':'인천','(not set)':'알 수 없음'})[v]||v}function deviceName(v){return ({desktop:'PC',mobile:'모바일',tablet:'태블릿'})[v]||v||'알 수 없음'}function duration(v){const s=Math.round(+v||0);return s<60?s+'초':Math.floor(s/60)+'분 '+s%60+'초'}function recentLabel(r){const d=r[0];return d.slice(4,6)+'/'+d.slice(6,8)+' '+d.slice(8,10)+':00 · '+deviceName(r[2])+' · '+localize(r[1])}function escapeHtml(v){const e=document.createElement('span');e.textContent=v;return e.innerHTML}
function drawChart(rows){const svg=document.querySelector('#chart');if(rows.length<2){svg.style.height='150px';svg.setAttribute('viewBox','0 0 800 180');svg.setAttribute('preserveAspectRatio','xMidYMid meet');svg.innerHTML='<text x="400" y="92" text-anchor="middle" fill="currentColor" opacity=".65" font-size="15">방문 기록이 이틀 이상 쌓이면 그래프가 표시됩니다</text>';chartLabels.innerHTML='';return}svg.style.height='';const vals=rows.map(r=>+r[1]),max=Math.max(1,...vals),w=800,vh=Math.max(170,Math.round(w*svg.clientHeight/Math.max(svg.clientWidth,1))),h=vh-24,p=12,left=34,pts=rows.map((r,i)=>[left+(w-left-p)*(i/Math.max(1,rows.length-1)),h-p-(h-p*2)*(+r[1]/max),r[0],r[1]]);const zones=pts.map((point,i)=>{const zoneLeft=i===0?0:(pts[i-1][0]+point[0])/2,right=i===pts.length-1?w:(point[0]+pts[i+1][0])/2;return [zoneLeft,right-zoneLeft,point[2],point[3]]}),divisions=Math.min(4,max),ticks=Array.from({length:divisions+1},(_,i)=>Math.round(max*i/divisions)).filter((v,i,a)=>a.indexOf(v)===i);svg.setAttribute('viewBox','0 0 '+w+' '+vh);svg.setAttribute('preserveAspectRatio','xMidYMid meet');const line=pts.map(p=>p.slice(0,2).join(',')).join(' '),area=pts.length?line+' '+pts.at(-1)[0]+','+h+' '+pts[0][0]+','+h:'',tickLines=ticks.map(value=>{const y=h-p-(h-p*2)*(value/max);return '<line class="gridline" x1="'+left+'" y1="'+y+'" x2="'+w+'" y2="'+y+'"/><text x="'+(left-8)+'" y="'+(y+4)+'" text-anchor="end" fill="currentColor" opacity=".55" font-size="11">'+value+'</text>'}).join('');svg.innerHTML='<defs><linearGradient id="areaGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#f5821f" stop-opacity=".28"/><stop offset="1" stop-color="#f5821f" stop-opacity="0"/></linearGradient></defs>'+tickLines+'<polygon class="area" points="'+area+'"/><polyline class="line" points="'+line+'"/>'+pts.map(p=>'<circle class="dot" data-date="'+p[2]+'" cx="'+p[0]+'" cy="'+p[1]+'" r="4"/>').join('')+zones.map(zone=>'<rect class="hit-area" data-date="'+zone[2]+'" x="'+zone[0]+'" y="0" width="'+zone[1]+'" height="'+vh+'" role="button" tabindex="0" aria-label="'+formatDate(zone[2])+' 방문자 '+zone[3]+'명"><title>'+formatDate(zone[2])+' · '+zone[3]+'명</title></rect>').join('');svg.querySelectorAll('.hit-area').forEach(zone=>{zone.addEventListener('click',()=>selectDate(zone.dataset.date));zone.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectDate(zone.dataset.date)}})});const labels=rows.length>7?[rows[0],rows[Math.floor(rows.length/2)],rows.at(-1)]:rows;chartLabels.innerHTML=labels.map(r=>'<span>'+formatDate(r[0])+'</span>').join('')}function formatDate(v){return v.slice(4,6)+'/'+v.slice(6,8)}
function setupDateControls(){if(document.getElementById('startDate'))return;const style=document.createElement('style');style.textContent='.ranges::before{display:none}.ranges{align-items:center;justify-content:flex-end;flex-wrap:wrap;gap:9px}.date-filter-label{color:var(--accent);font-size:13px;font-weight:700;margin-right:3px}.date-input{min-width:140px;padding:10px 12px;border:1px solid var(--line);border-radius:10px;background:var(--panel);color:var(--text);font:inherit}.date-separator{color:var(--muted)}.apply-range{border:1px solid var(--accent);background:var(--accent);color:#fff;border-radius:10px;padding:10px 14px;cursor:pointer}.chart .area,.chart .line{pointer-events:none}.hit-area{fill:transparent;cursor:pointer;transition:fill .16s ease}.hit-area:hover,.hit-area:focus,.hit-area.selected{fill:color-mix(in srgb,var(--accent) 10%,transparent);outline:none}.is-loading{position:relative;overflow:hidden;pointer-events:none}.is-loading::after{content:"불러오는 중";position:absolute;inset:0;z-index:5;display:grid;place-items:center;background:color-mix(in srgb,var(--panel) 78%,transparent);color:var(--accent);font-size:13px;font-weight:700;backdrop-filter:blur(2px)}@media(max-width:720px){.panel-head{align-items:flex-start;gap:14px;flex-direction:column}.ranges{justify-content:flex-start;width:100%}.date-input{min-width:0;flex:1}}';document.head.appendChild(style);document.querySelector('.ranges').innerHTML='<span class="date-filter-label">조회 기간</span><input id="startDate" class="date-input" type="date" aria-label="조회 시작일"><span class="date-separator">~</span><input id="endDate" class="date-input" type="date" aria-label="조회 종료일"><button class="apply-range" type="button" onclick="applyDateRange()">조회</button><button class="range active" data-days="7" type="button" onclick="setRange(7)">7일</button><button class="range" data-days="30" type="button" onclick="setRange(30)">30일</button>';setPresetDates(days)}
function setupTheme(){const saved=localStorage.getItem('dashboard_theme'),dark=saved?saved==='dark':false;document.documentElement.classList.add(dark?'dark':'light');const b=document.createElement('button');b.id='themeBtn';b.className='icon-btn';b.onclick=toggleTheme;document.querySelector('.actions').prepend(b);syncThemeButton()}function toggleTheme(){const root=document.documentElement,dark=!root.classList.contains('dark');root.classList.add('theme-transition');root.classList.remove('dark','light');root.classList.add(dark?'dark':'light');localStorage.setItem('dashboard_theme',dark?'dark':'light');syncThemeButton();setTimeout(()=>root.classList.remove('theme-transition'),450)}function syncThemeButton(){themeBtn.textContent=document.documentElement.classList.contains('dark')?'☀ 라이트':'☾ 다크'}function setPublicUi(){document.querySelector('.logo').textContent='⚙';document.querySelector('.brand h1').textContent='관리';document.querySelector('.subtitle').textContent='권한 확인이 필요합니다.';document.querySelector('#login p').innerHTML='<strong>관리자 인증</strong>허용된 Google 계정으로 로그인해주세요.'}function setAuthorizedUi(){document.documentElement.classList.add('authorized');document.title='Resume Analytics';document.querySelector('.brand h1').textContent='Resume Analytics';document.querySelector('.subtitle').textContent='이력서 방문 현황을 한눈에 확인하세요';setupDateControls()}
function syncSelectedDots(){const zones=Array.from(document.querySelectorAll('.hit-area')),coversAll=zones.length>0&&!!activeStart&&activeStart<=zones[0].dataset.date&&activeEnd>=zones.at(-1).dataset.date;document.querySelectorAll('.dot').forEach(dot=>dot.classList.toggle('in-range',!!activeStart&&dot.dataset.date>=activeStart&&dot.dataset.date<=activeEnd));zones.forEach(zone=>{zone.classList.remove('drag-selected');zone.classList.toggle('selected',!coversAll&&!!activeStart&&zone.dataset.date>=activeStart&&zone.dataset.date<=activeEnd)})}
function setupChartRange(){const svg=document.querySelector('#chart');let dragStart=-1,dragEnd=-1,suppressClick=false;const zones=()=>Array.from(svg.querySelectorAll('.hit-area'));const indexAt=clientX=>{const items=zones();if(!items.length)return-1;const box=svg.getBoundingClientRect(),view=svg.viewBox.baseVal,x=(clientX-box.left)/box.width*view.width;return items.findIndex(zone=>{const left=+zone.getAttribute('x'),right=left+(+zone.getAttribute('width'));return x>=left&&x<=right})};const preview=(a,b)=>{const min=Math.min(a,b),max=Math.max(a,b),items=zones();items.forEach((zone,i)=>zone.classList.toggle('drag-selected',i>=min&&i<=max));document.querySelectorAll('.dot').forEach(dot=>{const i=items.findIndex(zone=>zone.dataset.date===dot.dataset.date);dot.classList.toggle('drag-selected',i>=min&&i<=max)})};svg.onpointerdown=e=>{const i=indexAt(e.clientX);if(i<0)return;e.preventDefault();dragStart=dragEnd=i;svg.setPointerCapture?.(e.pointerId);preview(i,i)};svg.onpointermove=e=>{if(dragStart<0)return;const i=indexAt(e.clientX);if(i<0)return;dragEnd=i;preview(dragStart,dragEnd)};svg.onpointerup=e=>{if(dragStart<0)return;const items=zones(),first=items[Math.min(dragStart,dragEnd)]?.dataset.date,last=items[Math.max(dragStart,dragEnd)]?.dataset.date;dragStart=dragEnd=-1;suppressClick=true;svg.releasePointerCapture?.(e.pointerId);if(first&&last)applyGraphRange(first,last)};svg.onpointercancel=()=>{dragStart=dragEnd=-1;document.querySelectorAll('.drag-selected').forEach(el=>el.classList.remove('drag-selected'))};svg.addEventListener('click',e=>{if(!suppressClick)return;e.preventDefault();e.stopImmediatePropagation();suppressClick=false},true);new MutationObserver(syncSelectedDots).observe(svg,{childList:true})}
function setupFilterStyles(){const style=document.createElement('style');style.textContent='.apply-range{background:var(--text)!important;border-color:var(--text)!important;color:var(--panel)!important}.ranges.custom-range .date-filter-label{color:#2563eb}.ranges.custom-range .date-input{border-color:#3b82f6;box-shadow:0 0 0 3px color-mix(in srgb,#3b82f6 16%,transparent);background:color-mix(in srgb,#3b82f6 5%,var(--panel))}.ranges.custom-range .apply-range{background:#2563eb!important;border-color:#2563eb!important;color:#fff!important}.dot.in-range,.dot.drag-selected{fill:var(--accent)!important}.hit-area.selected{fill:color-mix(in srgb,#3b82f6 10%,transparent)}.hit-area.drag-selected{fill:color-mix(in srgb,#2563eb 30%,transparent)!important}';document.head.appendChild(style)}
window.onload=()=>{setPublicUi();setupTheme();setupFilterStyles();setupChartRange();google.accounts.id.initialize({client_id:'__CLIENT_ID__',callback:login});google.accounts.id.renderButton(document.querySelector('#button'),{theme:'outline',size:'large'});loadData(true)};
</script></body></html>`;

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname === "/") return new Response(HTML.replaceAll("__CLIENT_ID__", env.GOOGLE_CLIENT_ID), { headers: { "content-type": "text/html;charset=UTF-8", "cache-control": "no-store" } });
    if (url.pathname === "/api/session" && request.method === "POST") return createSession(request, env);
    if (url.pathname === "/api/logout" && request.method === "POST") return new Response(null, { status: 204, headers: { "set-cookie": "resume_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0" } });
    if (url.pathname === "/api/report") return report(request, env, Math.min(30, Math.max(7, Number(url.searchParams.get("days")) || 7)), url.searchParams.get("date"), url.searchParams.get("start"), url.searchParams.get("end"));
    return new Response("Not found", { status: 404 });
  }
};

async function report(request, env, days, requestedDate, requestedStart, requestedEnd) {
  if (!await validSession(request, env)) return new Response("Unauthorized", { status: 401 });
  try {
  const accessToken = await serviceAccessToken(env);
  const selectedDate = /^\d{4}-\d{2}-\d{2}$/.test(requestedDate || "") ? requestedDate : "";
  const customStart = /^\d{4}-\d{2}-\d{2}$/.test(requestedStart || "") ? requestedStart : "";
  const customEnd = /^\d{4}-\d{2}-\d{2}$/.test(requestedEnd || "") ? requestedEnd : "";
  const hasCustomRange = customStart && customEnd && customStart <= customEnd;
  const rangeStart = selectedDate || (hasCustomRange ? customStart : `${days-1}daysAgo`);
  const rangeEnd = selectedDate || (hasCustomRange ? customEnd : "today");
  const rangeDays = selectedDate ? 1 : (hasCustomRange ? daysBetween(customStart, customEnd) + 1 : days);
  const summaryDate = selectedDate || (hasCustomRange && rangeDays === 1 ? customStart : "today");
  const previousEnd = selectedDate || hasCustomRange ? shiftDate(rangeStart, -1) : `${days}daysAgo`;
  const previousStart = selectedDate || hasCustomRange ? shiftDate(previousEnd, -(rangeDays - 1)) : `${days*2-1}daysAgo`;
  const [today, week, previous, sources, cities, daily, pages, devices, hours, landings, recent] = await Promise.all([
    ga(env, accessToken, { dateRanges:[{startDate:summaryDate,endDate:summaryDate}],metrics:[{name:"activeUsers"}] }),
    ga(env, accessToken, { dateRanges:[{startDate:rangeStart,endDate:rangeEnd}],metrics:[{name:"activeUsers"},{name:"screenPageViews"}] }),
    ga(env, accessToken, { dateRanges:[{startDate:previousStart,endDate:previousEnd}],metrics:[{name:"activeUsers"}] }),
    ga(env, accessToken, { dateRanges:[{startDate:rangeStart,endDate:rangeEnd}],dimensions:[{name:"sessionSource"},{name:"sessionMedium"}],metrics:[{name:"activeUsers"}],orderBys:[{metric:{metricName:"activeUsers"},desc:true}],limit:"10" }),
    ga(env, accessToken, { dateRanges:[{startDate:rangeStart,endDate:rangeEnd}],dimensions:[{name:"city"}],metrics:[{name:"activeUsers"}],orderBys:[{metric:{metricName:"activeUsers"},desc:true}],limit:"10" }),
    ga(env, accessToken, { dateRanges:[{startDate:rangeStart,endDate:rangeEnd}],dimensions:[{name:"date"}],metrics:[{name:"activeUsers"}],orderBys:[{dimension:{dimensionName:"date"}}] }),
    ga(env, accessToken, { dateRanges:[{startDate:rangeStart,endDate:rangeEnd}],dimensions:[{name:"pagePath"}],metrics:[{name:"screenPageViews"},{name:"averageSessionDuration"}],orderBys:[{metric:{metricName:"screenPageViews"},desc:true}],limit:"8" }),
    ga(env, accessToken, { dateRanges:[{startDate:rangeStart,endDate:rangeEnd}],dimensions:[{name:"deviceCategory"}],metrics:[{name:"activeUsers"}],orderBys:[{metric:{metricName:"activeUsers"},desc:true}] }),
    ga(env, accessToken, { dateRanges:[{startDate:rangeStart,endDate:rangeEnd}],dimensions:[{name:"hour"}],metrics:[{name:"activeUsers"}],orderBys:[{dimension:{dimensionName:"hour"}}] }),
    ga(env, accessToken, { dateRanges:[{startDate:rangeStart,endDate:rangeEnd}],dimensions:[{name:"landingPage"}],metrics:[{name:"sessions"}],orderBys:[{metric:{metricName:"sessions"},desc:true}],limit:"8" }),
    ga(env, accessToken, { dateRanges:[{startDate:rangeStart,endDate:rangeEnd}],dimensions:[{name:"dateHour"},{name:"city"},{name:"deviceCategory"}],metrics:[{name:"activeUsers"}],orderBys:[{dimension:{dimensionName:"dateHour"},desc:true}],limit:"8" })
  ]);
  const currentUsers=Number(value(week,0)), previousUsers=Number(value(previous,0));
  const chartEnd=selectedDate||(hasCustomRange?customEnd:koreaToday()),chartStart=selectedDate||(hasCustomRange?customStart:shiftDate(chartEnd,-(days-1)));
  return Response.json({ selectedDate, rangeStart, rangeEnd, today:value(today,0), week:currentUsers, views:value(week,1), change:previousUsers?Math.round((currentUsers-previousUsers)/previousUsers*100):(currentUsers?100:0), sources:rows(sources), cities:rows(cities), daily:fillDaily(rows(daily),chartStart,chartEnd), pages:rows(pages), devices:rows(devices), hours:rows(hours), landings:rows(landings), recent:rows(recent) });
  } catch (error) {
    return new Response("GA 조회 오류: " + error.message, { status: 500 });
  }
}

function shiftDate(value, offset) { const date = new Date(value + "T00:00:00Z"); date.setUTCDate(date.getUTCDate() + offset); return date.toISOString().slice(0, 10); }
function daysBetween(start, end) { return Math.round((new Date(end + "T00:00:00Z") - new Date(start + "T00:00:00Z")) / 86400000); }
function koreaToday() { return new Intl.DateTimeFormat("en-CA", { timeZone:"Asia/Seoul", year:"numeric", month:"2-digit", day:"2-digit" }).format(new Date()); }
function fillDaily(data, start, end) { const values=new Map(data.map(row=>[row[0],row[1]])),result=[]; for(let date=start;date<=end;date=shiftDate(date,1)){const key=date.replaceAll("-","");result.push([key,values.get(key)||"0"])} return result; }

async function createSession(request, env) {
  const idToken = (request.headers.get("authorization") || "").replace(/^Bearer /, "");
  const identity = await fetch("https://oauth2.googleapis.com/tokeninfo?id_token=" + encodeURIComponent(idToken)).then(r => r.ok ? r.json() : null);
  if (!identity || identity.aud !== env.GOOGLE_CLIENT_ID || identity.email !== env.ALLOWED_EMAIL || identity.email_verified !== "true") return new Response("Forbidden", { status: 403 });
  const payload = toBase64Url(new TextEncoder().encode(JSON.stringify({ email: identity.email, exp: Math.floor(Date.now()/1000) + 604800 })));
  const signature = await signSession(payload, env);
  return new Response(null, { status: 204, headers: { "set-cookie": `resume_session=${payload}.${signature}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=604800` } });
}

async function validSession(request, env) {
  const raw = (request.headers.get("cookie") || "").split(";").map(v => v.trim()).find(v => v.startsWith("resume_session="))?.slice(15);
  if (!raw) return false;
  const [payload, signature] = raw.split(".");
  if (!payload || !signature || signature !== await signSession(payload, env)) return false;
  try { const data = JSON.parse(new TextDecoder().decode(fromBase64Url(payload))); return data.email === env.ALLOWED_EMAIL && data.exp > Date.now()/1000; } catch { return false; }
}
async function signSession(value, env) { const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(env.SERVICE_ACCOUNT_PRIVATE_KEY), { name:"HMAC", hash:"SHA-256" }, false, ["sign"]); return toBase64Url(new Uint8Array(await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(value)))); }
function toBase64Url(bytes) { return btoa(String.fromCharCode(...bytes)).replaceAll("+","-").replaceAll("/","_").replaceAll("=",""); }
function fromBase64Url(value) { const normalized=value.replaceAll("-","+").replaceAll("_","/"); return Uint8Array.from(atob(normalized+"=".repeat((4-normalized.length%4)%4)), c=>c.charCodeAt(0)); }

async function ga(env, token, body) {
  const r = await fetch(`https://analyticsdata.googleapis.com/v1beta/properties/${env.GA_PROPERTY_ID}:runReport`, { method:"POST", headers:{authorization:`Bearer ${token}`,"content-type":"application/json"}, body:JSON.stringify(body) });
  if (!r.ok) throw new Error(await r.text());
  return r.json();
}
function value(r,n){return r.rows?.[0]?.metricValues?.[n]?.value || "0"}
function rows(r){return (r.rows||[]).map(x=>[...(x.dimensionValues||[]).map(v=>v.value),...(x.metricValues||[]).map(v=>v.value)])}

async function serviceAccessToken(env) {
  const now = Math.floor(Date.now()/1000);
  const enc = x => btoa(JSON.stringify(x)).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");
  const unsigned = enc({alg:"RS256",typ:"JWT"})+"."+enc({iss:env.SERVICE_ACCOUNT_EMAIL,scope:"https://www.googleapis.com/auth/analytics.readonly",aud:"https://oauth2.googleapis.com/token",iat:now,exp:now+3600});
  const pem = env.SERVICE_ACCOUNT_PRIVATE_KEY.replace(/\\n/g,"\n");
  const keyBytes = Uint8Array.from(atob(pem.replace(/-----[^-]+-----/g,"").replace(/\s/g,"")),c=>c.charCodeAt(0));
  const key = await crypto.subtle.importKey("pkcs8",keyBytes,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]);
  const signature = await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,new TextEncoder().encode(unsigned));
  const jwt = unsigned+"."+btoa(String.fromCharCode(...new Uint8Array(signature))).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");
  const r = await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion:jwt})});
  if(!r.ok) throw new Error(await r.text());
  return (await r.json()).access_token;
}
