# build paths
source: Resume

# site settings
encoding: utf-8
baseurl: "/Resume"
url: "https://mdj0126.github.io"
thumbnail: "/assets/img/picture/profile-og.png"
title: "문동준 프로필"
desc: "Unity와 C#을 활용한 게임 클라이언트 개발자. 포트폴리오에서 프로젝트를 확인하세요!"
open_to_work: true
google_analytics: "G-6GHV7BHE5J"
public: true

# author settings
author:
  picture: "/assets/img/picture/profile.png"
  name_en: "Moon Dongjun"
  name_ko: "문동준"
  birth_date: "19930126"
  email: "ehdwns0126@naver.com"
  address: "경기도 부천시"
  job: "게임 클라이언트 개발자"
  job_start_date: "20180903"
  coffee_chat_url: "https://open.kakao.com/o/sWoSndmh"

# links
tistory: "https://moondongjun.tistory.com/"
github: "https://github.com/MDJ0126/"
linkedin: "https://www.linkedin.com/in/moondongjun/"

# build settings
exclude:
  - LICENSE
  - README.md

sass:
  sass_dir: _sass
  style: compressed
