encoding: utf-8
title: 문동준 포트폴리오
url: https://mdj0126.github.io
baseurl: /Portfolio
markdown: kramdown
defaults:
  - scope: { path: "_posts/company-projects", type: posts }
    values: { layout: post, category: company-projects, category_label: "COMPANY PROJECT", permalink: "/company-projects/:title/" }
  - scope: { path: "_posts/personal-projects", type: posts }
    values: { layout: post, category: personal-projects, category_label: "PERSONAL PROJECT", permalink: "/personal-projects/:title/" }
  - scope: { path: "_posts/coding-tests", type: posts }
    values: { layout: post, category: coding-tests, category_label: "ALGORITHM", permalink: "/coding-tests/:title/" }
exclude: [production.html]
